source 'https://rubygems.org'

gem 'activerecord', '~> 4.2'
gem 'omniauth-github'
gem 'pg'
gem 'rake'
gem "sinatra", "~> 2.0"
gem "sinatra-contrib"
gem 'sinatra-activerecord', '2.0.13'
gem 'sinatra-flash'
gem 'faker'
gem 'orderly'
gem 'rails-helper'

group :development, :test do
  gem 'capybara'
  gem 'launchy'
  gem 'dotenv'
end

group :test do
  gem 'pry'
  gem 'rspec'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'factory_bot'
end
