source 'https://rubygems.org'

gem 'activerecord', '~> 4.2'
gem 'pg'
gem 'rake'
gem 'sinatra', "~> 2.0"
gem 'sinatra-activerecord', '~> 2.0.9'
gem 'sinatra-contrib'
gem 'faker'

group :test, :development do
  gem 'capybara'
  gem 'pry'
  gem 'rspec'
end
